"""folder scan verdict cache

Revision ID: 02a82cba1d8a
Revises: 60d08446fa35
Create Date: 2026-08-13 16:00:50.299580

"""
from alembic import op
import sqlalchemy as sa


revision = '02a82cba1d8a'
down_revision = '60d08446fa35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('folder_scan_cache',
    sa.Column('folder', sa.Text(), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('outcome', sa.String(length=32), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=True),
    sa.Column('artist_name', sa.String(length=500), nullable=True),
    sa.Column('album', sa.String(length=500), nullable=True),
    sa.Column('matched', sa.Integer(), nullable=True),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.Column('checked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('folder')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('folder_scan_cache')
    # ### end Alembic commands ###
