"""where a photograph was taken and how

Revision ID: 04c180cdd89f
Revises: af8bb6d2e49b
Create Date: 2026-08-26 23:04:00.562839

"""
from alembic import op
import sqlalchemy as sa


revision = '04c180cdd89f'
down_revision = 'af8bb6d2e49b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photos', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('photos', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('photos', sa.Column('altitude', sa.Float(), nullable=True))
    op.add_column('photos', sa.Column('lens', sa.String(length=96), nullable=False, server_default=''))
    op.add_column('photos', sa.Column('focal_mm', sa.Float(), nullable=True))
    op.add_column('photos', sa.Column('aperture', sa.Float(), nullable=True))
    op.add_column('photos', sa.Column('iso', sa.Integer(), nullable=True))
    op.add_column('photos', sa.Column('shutter', sa.String(length=24), nullable=False, server_default=''))
    op.alter_column('photos', 'lens', server_default=None)
    op.alter_column('photos', 'shutter', server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photos', 'shutter')
    op.drop_column('photos', 'iso')
    op.drop_column('photos', 'aperture')
    op.drop_column('photos', 'focal_mm')
    op.drop_column('photos', 'lens')
    op.drop_column('photos', 'altitude')
    op.drop_column('photos', 'longitude')
    op.drop_column('photos', 'latitude')
    # ### end Alembic commands ###
