"""manual artwork choice

Revision ID: 0d8c2efb0e74
Revises: 02a82cba1d8a
Create Date: 2026-08-14 10:43:03.334099

"""
from alembic import op
import sqlalchemy as sa


revision = '0d8c2efb0e74'
down_revision = '02a82cba1d8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('chosen_manual', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'chosen_manual')
    # ### end Alembic commands ###
