"""a title knows where it streams

Revision ID: 0ef7bfffd717
Revises: 5e0ca9338357
Create Date: 2026-09-16 15:15:22.320269

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '0ef7bfffd717'
down_revision = '5e0ca9338357'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('streaming',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('media_type', sa.String(), nullable=False),
    sa.Column('tmdb_id', sa.Integer(), nullable=False),
    sa.Column('services', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('asked_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('media_type', 'tmdb_id')
    )
    op.create_index(op.f('ix_streaming_asked_at'), 'streaming', ['asked_at'], unique=False)
    op.create_index(op.f('ix_streaming_checked_at'), 'streaming', ['checked_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_streaming_checked_at'), table_name='streaming')
    op.drop_index(op.f('ix_streaming_asked_at'), table_name='streaming')
    op.drop_table('streaming')
    # ### end Alembic commands ###
