"""file provenance

Revision ID: 154c6a7e3e8b
Revises: 0d8c2efb0e74
Create Date: 2026-08-14 12:21:42.117732

"""
from alembic import op
import sqlalchemy as sa


revision = '154c6a7e3e8b'
down_revision = '0d8c2efb0e74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('download_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_files_download_id'), 'files', ['download_id'], unique=False)
    op.create_foreign_key(None, 'files', 'downloads', ['download_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'files', type_='foreignkey')
    op.drop_index(op.f('ix_files_download_id'), table_name='files')
    op.drop_column('files', 'download_id')
    # ### end Alembic commands ###
