"""settings table

Revision ID: 272e4ee2c716
Revises: b024ac12153f
Create Date: 2026-08-11 12:20:40.258695

"""
from alembic import op
import sqlalchemy as sa


revision = '272e4ee2c716'
down_revision = 'b024ac12153f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('settings')
    # ### end Alembic commands ###
