"""files channels

Revision ID: 4674117ca92c
Revises: 154c6a7e3e8b
Create Date: 2026-08-14 15:27:46.588935

"""
from alembic import op
import sqlalchemy as sa


revision = '4674117ca92c'
down_revision = '154c6a7e3e8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('channels', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'channels')
    # ### end Alembic commands ###
