"""where the credits begin

Revision ID: 4da9ba073143
Revises: 97eb96ccbc6f
Create Date: 2026-09-15 22:27:27.346644

"""
from alembic import op
import sqlalchemy as sa


revision = '4da9ba073143'
down_revision = '97eb96ccbc6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video_files', sa.Column('credits_s', sa.Float(), nullable=True))
    op.add_column('video_files', sa.Column('credits_by', sa.String(), server_default='', nullable=False))
    op.add_column('video_files', sa.Column('credits_read_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video_files', 'credits_read_at')
    op.drop_column('video_files', 'credits_by')
    op.drop_column('video_files', 'credits_s')
    # ### end Alembic commands ###
