"""a person needs no cover column

Revision ID: 516755595000
Revises: 54e60649531e
Create Date: 2026-08-26 20:58:14.445948

"""
from alembic import op
import sqlalchemy as sa


revision = '516755595000'
down_revision = '54e60649531e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_photo_people_cover_face'), 'photo_people', type_='foreignkey')
    op.drop_column('photo_people', 'cover_face_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photo_people', sa.Column('cover_face_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('fk_photo_people_cover_face'), 'photo_people', 'photo_faces', ['cover_face_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
