"""a person has a given and a family name

Revision ID: 54e60649531e
Revises: a5541c172c58
Create Date: 2026-08-26 20:52:02.635355

"""
from alembic import op
import sqlalchemy as sa


revision = '54e60649531e'
down_revision = 'a5541c172c58'
branch_labels = None
depends_on = None


def upgrade():
    # a default, or the columns cannot be added to a table that already holds
    # people; the names are split out of what is there and the default then goes
    op.add_column('photo_people',
                  sa.Column('given_name', sa.String(length=80),
                            nullable=False, server_default=''))
    op.add_column('photo_people',
                  sa.Column('family_name', sa.String(length=80),
                            nullable=False, server_default=''))
    # the family name is the last word and the given name is everything before
    # it, which is how these names were typed. A single word is a given name:
    # somebody called only Baka has no surname, she has a name
    op.execute("""
        UPDATE photo_people SET
            given_name = CASE WHEN position(' ' in btrim(name)) = 0 THEN btrim(name)
                              ELSE btrim(left(btrim(name), length(btrim(name))
                                   - position(' ' in reverse(btrim(name))))) END,
            family_name = CASE WHEN position(' ' in btrim(name)) = 0 THEN ''
                               ELSE right(btrim(name),
                                    position(' ' in reverse(btrim(name))) - 1) END
    """)
    op.create_index(op.f('ix_photo_people_family_name'), 'photo_people',
                    ['family_name'], unique=False)
    op.alter_column('photo_people', 'given_name', server_default=None)
    op.alter_column('photo_people', 'family_name', server_default=None)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_photo_people_family_name'), table_name='photo_people')
    op.drop_column('photo_people', 'family_name')
    op.drop_column('photo_people', 'given_name')
    # ### end Alembic commands ###
