"""add tidal_id to artist/release/track

Revision ID: 60d08446fa35
Revises: eb668d0ebf87
Create Date: 2026-08-13 08:25:25.645424

"""
from alembic import op
import sqlalchemy as sa


revision = '60d08446fa35'
down_revision = 'eb668d0ebf87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('tidal_id', sa.BigInteger(), nullable=True))
    op.create_unique_constraint(None, 'artists', ['tidal_id'])
    op.add_column('releases', sa.Column('tidal_id', sa.BigInteger(), nullable=True))
    op.create_unique_constraint(None, 'releases', ['tidal_id'])
    op.add_column('tracks', sa.Column('tidal_id', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tracks', 'tidal_id')
    op.drop_constraint(None, 'releases', type_='unique')
    op.drop_column('releases', 'tidal_id')
    op.drop_constraint(None, 'artists', type_='unique')
    op.drop_column('artists', 'tidal_id')
    # ### end Alembic commands ###
