"""which country a photograph is in

Revision ID: 7e9c17adca37
Revises: 96c66eace17d
Create Date: 2026-08-27 10:56:30.916209

"""
from alembic import op
import sqlalchemy as sa


revision = '7e9c17adca37'
down_revision = '96c66eace17d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photos', sa.Column('country', sa.String(length=2), nullable=False, server_default=''))
    op.create_index(op.f('ix_photos_country'), 'photos', ['country'], unique=False)
    op.create_index(op.f('ix_photos_place'), 'photos', ['place'], unique=False)
    op.alter_column('photos', 'country', server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_photos_place'), table_name='photos')
    op.drop_index(op.f('ix_photos_country'), table_name='photos')
    op.drop_column('photos', 'country')
    # ### end Alembic commands ###
