"""photographs shared by link

Revision ID: 801e45d4292e
Revises: 975df1d67bba
Create Date: 2026-09-24 12:24:59.404085

"""
from alembic import op
import sqlalchemy as sa


revision = '801e45d4292e'
down_revision = '975df1d67bba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('photo_shares',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key_hash', sa.LargeBinary(length=32), nullable=False),
    sa.Column('made_by', sa.String(length=64), nullable=False),
    sa.Column('made_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash')
    )
    op.create_table('photo_share_items',
    sa.Column('share_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('photo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['photo_id'], ['photos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['share_id'], ['photo_shares.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('share_id', 'position')
    )
    op.create_index(op.f('ix_photo_share_items_photo_id'), 'photo_share_items', ['photo_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_photo_share_items_photo_id'), table_name='photo_share_items')
    op.drop_table('photo_share_items')
    op.drop_table('photo_shares')
    # ### end Alembic commands ###
