"""where a birth date came from

Revision ID: 96c66eace17d
Revises: a1166e632e83
Create Date: 2026-08-27 10:31:05.553229

"""
from alembic import op
import sqlalchemy as sa


revision = '96c66eace17d'
down_revision = 'a1166e632e83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photo_people', sa.Column('born_source', sa.String(length=16), nullable=False, server_default=''))
    op.add_column('photo_people', sa.Column('contact_id', sa.String(length=120), nullable=False, server_default=''))
    op.create_index(op.f('ix_photo_people_contact_id'), 'photo_people', ['contact_id'], unique=False)
    op.alter_column('photo_people', 'born_source', server_default=None)
    op.alter_column('photo_people', 'contact_id', server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_photo_people_contact_id'), table_name='photo_people')
    op.drop_column('photo_people', 'contact_id')
    op.drop_column('photo_people', 'born_source')
    # ### end Alembic commands ###
