"""where the opening titles are

Revision ID: 975df1d67bba
Revises: 9a863d4293bd
Create Date: 2026-09-24 12:02:48.697554

"""
from alembic import op
import sqlalchemy as sa


revision = '975df1d67bba'
down_revision = '9a863d4293bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video_files', sa.Column('intro_s', sa.Float(), nullable=True))
    op.add_column('video_files', sa.Column('intro_end_s', sa.Float(), nullable=True))
    op.add_column('video_files', sa.Column('intro_read_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video_files', 'intro_read_at')
    op.drop_column('video_files', 'intro_end_s')
    op.drop_column('video_files', 'intro_s')
    # ### end Alembic commands ###
