"""who won what

Revision ID: 97eb96ccbc6f
Revises: be4d0eccd7b0
Create Date: 2026-09-15 18:11:50.126635

"""
from alembic import op
import sqlalchemy as sa


revision = '97eb96ccbc6f'
down_revision = 'be4d0eccd7b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('award_titles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('media_type', sa.String(), nullable=False),
    sa.Column('tmdb_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('poster_url', sa.String(), nullable=True),
    sa.Column('vote_average', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('media_type', 'tmdb_id')
    )
    op.create_table('award_wins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('award', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('title_id', sa.Integer(), nullable=False),
    sa.Column('refreshed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['title_id'], ['award_titles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('award', 'year', 'title_id')
    )
    op.create_index(op.f('ix_award_wins_award'), 'award_wins', ['award'], unique=False)
    op.create_index(op.f('ix_award_wins_title_id'), 'award_wins', ['title_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_award_wins_title_id'), table_name='award_wins')
    op.drop_index(op.f('ix_award_wins_award'), table_name='award_wins')
    op.drop_table('award_wins')
    op.drop_table('award_titles')
    # ### end Alembic commands ###
