"""a box is let in, not signed in

Revision ID: 9ad032b5a541
Revises: bb2653a4830c
Create Date: 2026-08-29 05:53:31.737441

"""
from alembic import op
import sqlalchemy as sa


revision = '9ad032b5a541'
down_revision = 'bb2653a4830c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=True),
    sa.Column('token', sa.String(length=64), nullable=True),
    sa.Column('module', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('let_in_by', sa.String(length=64), nullable=False),
    sa.Column('let_in_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('token')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('devices')
    # ### end Alembic commands ###
