"""what the place is called

Revision ID: a1166e632e83
Revises: 04c180cdd89f
Create Date: 2026-08-27 08:14:27.365838

"""
from alembic import op
import sqlalchemy as sa


revision = 'a1166e632e83'
down_revision = '04c180cdd89f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photos', sa.Column('place', sa.String(length=120), nullable=False, server_default=''))
    op.add_column('photos', sa.Column('place_source', sa.String(length=16), nullable=False, server_default=''))
    op.alter_column('photos', 'place', server_default=None)
    op.alter_column('photos', 'place_source', server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photos', 'place_source')
    op.drop_column('photos', 'place')
    # ### end Alembic commands ###
