"""sharpness on a face

Revision ID: a5541c172c58
Revises: d7a91c4e8b52
Create Date: 2026-08-26 19:14:57.398221

"""
from alembic import op
import sqlalchemy as sa


revision = 'a5541c172c58'
down_revision = 'd7a91c4e8b52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photo_faces', sa.Column('sharpness', sa.Float(), nullable=True))
    op.create_index(op.f('ix_photo_faces_sharpness'), 'photo_faces', ['sharpness'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_photo_faces_sharpness'), table_name='photo_faces')
    op.drop_column('photo_faces', 'sharpness')
    # ### end Alembic commands ###
