"""a face keeps its landmarks

Revision ID: af8bb6d2e49b
Revises: d82880384087
Create Date: 2026-08-26 22:38:53.153736

"""
from alembic import op
import sqlalchemy as sa


revision = 'af8bb6d2e49b'
down_revision = 'd82880384087'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photo_faces', sa.Column('landmarks', sa.ARRAY(sa.Float()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photo_faces', 'landmarks')
    # ### end Alembic commands ###
