"""initial schema

Revision ID: b024ac12153f
Revises: 
Create Date: 2026-08-11 12:06:36.498401

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'b024ac12153f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('deezer_id', sa.BigInteger(), nullable=True),
    sa.Column('spotify_id', sa.String(length=64), nullable=True),
    sa.Column('discogs_id', sa.BigInteger(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('deezer_id')
    )
    op.create_table('releases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('deezer_id', sa.BigInteger(), nullable=True),
    sa.Column('spotify_id', sa.String(length=64), nullable=True),
    sa.Column('discogs_id', sa.BigInteger(), nullable=True),
    sa.Column('release_date', sa.String(length=10), nullable=True),
    sa.Column('record_type', sa.String(length=32), nullable=True),
    sa.Column('cover_url', sa.Text(), nullable=True),
    sa.Column('track_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('none', 'wanted', 'searching', 'downloading', 'complete', 'failed', name='releasestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('deezer_id')
    )
    op.create_table('downloads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('release_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.Enum('slskd', 'sabnzbd', 'tidal', name='channelname'), nullable=False),
    sa.Column('status', sa.Enum('queued', 'downloading', 'importing', 'complete', 'failed', name='downloadstatus'), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('job_ref', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['release_id'], ['releases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tracks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('release_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('duration_sec', sa.Integer(), nullable=True),
    sa.Column('deezer_id', sa.BigInteger(), nullable=True),
    sa.Column('file_path', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['release_id'], ['releases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tracks')
    op.drop_table('downloads')
    op.drop_table('releases')
    op.drop_table('artists')
    # ### end Alembic commands ###
