"""music file tags

Revision ID: b0606b2e26bc
Revises: 9ad032b5a541
Create Date: 2026-09-10 07:28:14.042345

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'b0606b2e26bc'
down_revision = '9ad032b5a541'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('music_files', sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('music_files', 'tags')
    # ### end Alembic commands ###
