"""a person has one standing, not two flags

Two booleans were being asked what is really one question. `owner` said who may
change things and, by implication, who is one of the household; nothing said
whether somebody is here for the evening. Three named standings say all of it
once.

The order matters and the autogenerated form had it wrong: the column is added,
every owner is carried into it, and only then does the old flag go. Dropping
first would leave the install with no admin, and an install with no admin has
nobody who can make one — the lock-out is silent and complete.

Revision ID: bb2653a4830c
Revises: c1d0faces
Create Date: 2026-08-29 05:10:13.367611

"""
from alembic import op
import sqlalchemy as sa


revision = 'bb2653a4830c'
down_revision = 'c1d0faces'
branch_labels = None
depends_on = None


def upgrade():
    op.add_column('users', sa.Column('role', sa.String(length=8),
                                     server_default='user', nullable=False))
    op.execute("UPDATE users SET role = 'admin' WHERE owner")
    op.drop_column('users', 'owner')


def downgrade():
    op.add_column('users', sa.Column('owner', sa.BOOLEAN(),
                                     server_default=sa.text('false'),
                                     autoincrement=False, nullable=False))
    # a guest going back to a world with two kinds of person becomes the lesser
    # of them, which is the only honest answer this direction has
    op.execute("UPDATE users SET owner = true WHERE role = 'admin'")
    op.drop_column('users', 'role')
