"""where in a recording a face was

Revision ID: be4d0eccd7b0
Revises: b0606b2e26bc
Create Date: 2026-09-11 08:45:26.783436

"""
from alembic import op
import sqlalchemy as sa


revision = 'be4d0eccd7b0'
down_revision = 'b0606b2e26bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photo_faces', sa.Column('at_seconds', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photo_faces', 'at_seconds')
    # ### end Alembic commands ###
