"""the centroid index is partial

Revision ID: d82880384087
Revises: fff661924386
Create Date: 2026-08-26 22:22:05.229146

"""
from alembic import op
import sqlalchemy as sa


revision = 'd82880384087'
down_revision = 'fff661924386'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_photo_face_clusters_centroid'), table_name='photo_face_clusters', postgresql_ops={'centroid': 'halfvec_cosine_ops'}, postgresql_using='hnsw')
    op.create_index('ix_photo_face_clusters_compared', 'photo_face_clusters', ['centroid'], unique=False, postgresql_using='hnsw', postgresql_ops={'centroid': 'halfvec_cosine_ops'}, postgresql_where=sa.text('centroid IS NOT NULL AND (faces_at >= 8 OR person_id IS NOT NULL)'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_photo_face_clusters_compared', table_name='photo_face_clusters', postgresql_using='hnsw', postgresql_ops={'centroid': 'halfvec_cosine_ops'}, postgresql_where=sa.text('centroid IS NOT NULL AND (faces_at >= 8 OR person_id IS NOT NULL)'))
    op.create_index(op.f('ix_photo_face_clusters_centroid'), 'photo_face_clusters', ['centroid'], unique=False, postgresql_ops={'centroid': 'halfvec_cosine_ops'}, postgresql_using='hnsw')
    # ### end Alembic commands ###
