"""artist enriched_at

Revision ID: f2eaad06d0ca
Revises: 1ddf56ee5f33
Create Date: 2026-08-12 11:48:49.203318

"""
from alembic import op
import sqlalchemy as sa


revision = 'f2eaad06d0ca'
down_revision = '1ddf56ee5f33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('enriched_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artists', 'enriched_at')
    # ### end Alembic commands ###
