"""a download remembers which post it took

Revision ID: f90e6a6aa828
Revises: 036f0b65a315
Create Date: 2026-09-17 08:06:49.435329

"""
from alembic import op
import sqlalchemy as sa


revision = 'f90e6a6aa828'
down_revision = '036f0b65a315'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video_downloads', sa.Column('release_guid', sa.String(), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video_downloads', 'release_guid')
    # ### end Alembic commands ###
