"""a cluster keeps its centroid

Revision ID: fff661924386
Revises: 516755595000
Create Date: 2026-08-26 22:10:24.431479

"""
from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


revision = 'fff661924386'
down_revision = '516755595000'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photo_face_clusters', sa.Column('centroid', pgvector.sqlalchemy.halfvec.HALFVEC(dim=512), nullable=True))
    op.add_column('photo_face_clusters', sa.Column('faces_at', sa.Integer(), nullable=True))
    op.create_index('ix_photo_face_clusters_centroid', 'photo_face_clusters', ['centroid'], unique=False, postgresql_using='hnsw', postgresql_ops={'centroid': 'halfvec_cosine_ops'})
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_photo_face_clusters_centroid', table_name='photo_face_clusters', postgresql_using='hnsw', postgresql_ops={'centroid': 'halfvec_cosine_ops'})
    op.drop_column('photo_face_clusters', 'faces_at')
    op.drop_column('photo_face_clusters', 'centroid')
    # ### end Alembic commands ###
